-- Doctrine Migration File Generated on 2025-12-30 11:24:08

-- Version DoctrineMigrations\Version20251228121415
CREATE TABLE membre (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT NOT NULL, date DATETIME NOT NULL, UNIQUE INDEX UNIQ_F6B4FB29FB88E14F (utilisateur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE sikla0 (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT NOT NULL, date DATETIME NOT NULL, realise DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_5F83E3FCFB88E14F (utilisateur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE transaction (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT NOT NULL, type_id INT NOT NULL, montant INT NOT NULL, date DATETIME NOT NULL, INDEX IDX_723705D1FB88E14F (utilisateur_id), INDEX IDX_723705D1C54C8C93 (type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE type_transaction (id INT AUTO_INCREMENT NOT NULL, libelle VARCHAR(255) NOT NULL, signe INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE utilisateur (id INT NOT NULL, parent_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, code VARCHAR(7) NOT NULL, adresse VARCHAR(255) DEFAULT NULL, telephone VARCHAR(30) DEFAULT NULL, fokontany VARCHAR(255) DEFAULT NULL, activite VARCHAR(255) DEFAULT NULL, nif VARCHAR(50) DEFAULT NULL, personne VARCHAR(30) NOT NULL, date DATETIME NOT NULL, solde INT NOT NULL, UNIQUE INDEX UNIQ_1D1C63B3E7927C74 (email), UNIQUE INDEX UNIQ_1D1C63B377153098 (code), INDEX IDX_1D1C63B3727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', available_at DATETIME NOT NULL COMMENT '(DC2Type:datetime_immutable)', delivered_at DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
ALTER TABLE membre ADD CONSTRAINT FK_F6B4FB29FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id);
ALTER TABLE sikla0 ADD CONSTRAINT FK_5F83E3FCFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id);
ALTER TABLE transaction ADD CONSTRAINT FK_723705D1FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id);
ALTER TABLE transaction ADD CONSTRAINT FK_723705D1C54C8C93 FOREIGN KEY (type_id) REFERENCES type_transaction (id);
ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B3727ACA70 FOREIGN KEY (parent_id) REFERENCES utilisateur (id);

        INSERT INTO type_transaction (libelle,signe) VALUES 
        ('Depot',1),
        ('Retrait',-1),
        ('Investissement Sikla 0',-1),
        ('Recompense Sikla 0',1)
        ;
